blank_issues_enabled: false
contact_links:
  - name: Questions or need help
    url: https://github.com/opentiny/ng/discussions
    about: Add this WeChat(opentiny), we will invite you to the WeChat discussion group later.
